<?xml version="1.0"?>
<?model_format xml?>
<package format="3">
<name>scan_automation</name>
<version>0.0.0</version>
<description>Isolated automated dataset generation package</description>
<maintainer email="user@todo.todo">user</maintainer>
<license>Apache-2.0</license>
<buildtool_depend>ament_cmake</buildtool_depend>
<depend>rclcpp</depend>
<depend>sensor_msgs</depend>
<depend>std_msgs</depend>
<depend>cv_bridge</depend>
<depend>moveit_ros_planning_interface</depend>
<depend>opencv</depend>
<depend>controller_manager_msgs</depend>   <!-- ADD THIS -->
<exec_depend>ros_gz_bridge</exec_depend>   <!-- for /turntable/cmd_vel bridge in the launch file -->
<export>
<build_type>ament_cmake</build_type>
</export>
</package>