controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: false   # <-- MUST be false

    arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_group_controller:
  ros__parameters:
    use_sim_time: false   # <-- MUST be false
    joints:
      - 1_Joint
      - 2_Joint
      - 3_Joint
      - 4_Joint
      - 5_Joint
      - 6_Joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: false   # <-- MUST be false